- package-lock.json
- package.json
- src/shared/ui/Button/index.tsx
- tailwind.config.js
> feat: 버튼 공유 컴포넌트 퍼블리싱

- src/view/main/ui/MainPage/index.tsx
- src/widget/main/ui/Inform/index.tsx
> fix: main 반응형

- src/app/post/[id].tsx
- src/app/transaction.tsx
- src/entity/post/ui/miniProfile/index.tsx
- src/shared/ui/Button/index.tsx
- src/view/post/ui/PostPage/index.tsx
- src/view/transaction/ui/TransactionPage/index.tsx
> feat: 게시글 상세 페이지와 게시글 목록 페이지 퍼블리싱

- src/shared/ui/Button/index.tsx
- src/shared/ui/Header/index.tsx
- src/view/post/ui/PostPage/index.tsx
- src/view/transaction/ui/TransactionPage/index.tsx
> fix: layout 

- src/app/index.tsx
- src/entity/signin/ui/SigninForm/index.tsx
- src/entity/signup/ui/SignupForm/index.tsx
- src/shared/ui/Header/index.tsx
- src/view/editProfile/ui/editProfilePage/index.tsx
- src/view/main/ui/MainPage/index.tsx
- src/view/notice/ui/NoticeDetailPage/index.tsx
- src/view/notice/ui/NoticePage/index.tsx
- src/view/post/ui/PostPage/index.tsx
- src/view/posts/ui/PostsPage/index.tsx
- src/view/product/itemForm/ui/ItemFormPage/index.tsx
- src/view/profile/ui/ProfilePage/index.tsx
- src/view/transaction/ui/TransactionPage/index.tsx
> iterm fom 페이지 ui 깨짐 문제 해결

- package-lock.json
- package.json
- src/shared/api/getPosts.ts
- src/shared/ui/Post/index.tsx
- src/view/product/itemForm/ui/ItemFormPage/index.tsx
> fix: post 이미지 안뜨는 문제 수정

- src/view/transaction/ui/TransactionPage/index.tsx
> post 페이지에 pull to refresh 기능을 추가했습니다
> feat: pull to refresh

- src/entity/post/api/deletePost.ts
- src/entity/post/index.ts
- src/entity/post/model/useDeletePost.ts
- src/entity/product/itemForm/model/useCreateItem.ts
- src/shared/ui/Post/index.tsx
- src/view/post/ui/PostPage/index.tsx
- src/view/transaction/ui/TransactionPage/index.tsx
관련된 이슈:
https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/43
> Feat: 게시글 삭제 로직 구현 

- src/entity/auth/model/authSchema.ts
- src/entity/auth/model/usePhoneVerification.ts
- src/shared/lib/errorHandler.ts
- src/widget/signin/ui/NicknameStep/index.tsx
- src/widget/signin/ui/PasswordStep/index.tsx
- src/widget/signup/ui/Complete/index.tsx
- src/widget/signup/ui/NameStep/index.tsx
- src/widget/signup/ui/NicknameStep/index.tsx
연관된 이슈: 
https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/48
https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/49
> Fix: 로그인 사용성 개선

- src/view/transaction/ui/TransactionPage/index.tsx
- 디자인과 일치하게 간격 계산 로직을 도입하고 패딩을 조정했어요.
- 안드로이드와 동일하게 슬라이드 애니메이션을 적용했습니다.
https://github.com/user-attachments/assets/edd9e9f3-fa1f-41e5-8fc3-b5049895e1a9
연관된 이슈:
https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/54
> Fix: 모드 선택 버튼 스타일 변경

- src/entity/profile/ui/Information/index.tsx
- src/entity/reviews/ui/ReviewPost/index.tsx
- src/view/profile/ui/ProfilePage/index.tsx
- src/widget/profile/ui/Active/index.tsx
> fix: profle style

- src/app/notification/[id]/index.tsx
- src/widget/product/itemForm/ui/ItemFormConfirm/index.tsx
- 글작성 페이지에서 ui가 뭉쳐서 깨지는 문제를 해결했습니다
> fix: 글작성 페이지 ui가 깨지는 문제

- src/entity/auth/api/signin.ts
- src/entity/auth/api/signup.ts
- src/entity/auth/model/useSignout.ts
- src/entity/chat/api/findChatRoom.ts
- src/shared/lib/axios.ts
- src/view/notice/ui/NoticePage/index.tsx
- src/view/profile/ui/ProfilePage/index.tsx
연관된 이슈:
https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/70
https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/71
https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/72
> Fix: 토큰 관련 로직 문제들 해결

- src/entity/post/api/report.ts
- src/entity/post/model/useReport.ts
- src/entity/post/ui/ReportModal/index.tsx
- src/view/post/ui/PostPage/index.tsx
연관된 이슈:
https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/65
> Fix: 신고 타입에 따라 sourceId 다르게 주게끔 수정했습니다 

- src/entity/post/model/useReport.ts
- src/entity/post/ui/ReportModal/index.tsx
- src/shared/ui/ImageUploader/index.tsx
- src/view/product/itemForm/ui/ItemFormPage/index.tsx
- src/widget/product/itemForm/ui/ItemFormContents/index.tsx
- src/widget/product/itemForm/ui/ItemFormRenderButton/index.tsx
- src/widget/product/itemForm/ui/ItemFormRenderContent/index.tsx
- 업로드 실패 상태 추가
- 상태를 상위 컴포넌트에 전파
연관된 이슈:
https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/53
> Fix: 이미지 업로더 상태 처리 개선

- src/entity/auth/lib/userSessionService.ts
- src/entity/auth/model/useSignout.ts
- src/view/profile/model/useGetMyProfile.ts
- src/view/profile/ui/ProfilePage/index.tsx
이전에 로그인했던 사용자의 정보를 가져오는 문제를 해결했습니다.
연관된 이슈:
https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/75
> Fix: 멤버 관련 캐시 문제 

- src/view/profile/api/getMyPosts.ts
- src/view/profile/model/useGetMyPosts.ts
- src/view/profile/ui/ProfilePage/index.tsx
엔드포인트 기존 /post/member/{id}에서 /post/current로 수정
> Fix: 내 프로필에서 게시글 조회할 때 

- src/entity/auth/api/withdrawal.ts
- src/entity/auth/index.ts
- src/entity/auth/model/useWithdrawal.ts
- src/entity/profile/ui/Information/index.tsx
- src/shared/ui/BottomSheetModalWrapper/index.tsx
> Feat: 회원 탈퇴 로직 구현 

- src/entity/auth/model/useSignout.ts
액세스토큰을 지운 후 /signout 요청을 보내서 401에러가 떠버리는 문제를 해결했습니다. 
~~전에 했었던 것 같은데 날라간듯~~
> Fix: 토큰 제거 순서 변경

- package-lock.json
- package.json
> Chore: update package version

- src/entity/chat/model/useChatSocket.ts
- src/widget/chat/model/useChatMessages.ts
resolve https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/82
> fix: 채팅 sendMessage의 content값에 null 대신 공백을 보내도록 수정했습니다.

- src/entity/auth/api/sendSms.ts
- src/entity/auth/api/signin.ts
- src/entity/auth/api/signout.ts
- src/entity/auth/api/signup.ts
- src/entity/auth/api/verifySms.ts
- src/entity/auth/api/withdrawal.ts
- src/entity/auth/model/authSchema.ts
- src/entity/chat/api/createChatRoom.ts
- src/entity/chat/api/findChatRoom.ts
- src/entity/chat/api/getChatMessages.ts
- src/entity/chat/api/getChatRooms.ts
- src/entity/chat/api/markChatAsRead.ts
- src/entity/chat/ui/TradeEmbed/index.tsx
- src/entity/post/api/cancelReservation.ts
- src/entity/post/api/createReview.ts
- src/entity/post/api/deletePost.ts
- src/entity/post/api/editPost.ts
- src/entity/post/api/getItem.ts
- src/entity/post/api/makeReservation.ts
- src/entity/post/api/report.ts
- src/entity/post/api/requestTrade.ts
- src/entity/post/hooks/useTradeRequest.ts
- src/entity/post/model/useReport.ts
- src/entity/write/itemForm/api/createItem.ts
- src/shared/lib/errorHandler.ts
- src/shared/lib/useChatNavigation.ts
- src/shared/ui/Header/index.tsx
- src/shared/ui/ImageUploader/index.tsx
- src/view/chat/ui/ChatRoomPage/index.tsx
- src/widget/chat/ui/ChatRoomHeader/index.tsx
Resolve https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/123, https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/117, https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/118, https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/115, https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/114, https://github.com/School-of-Company/Gwangsan-Crossplatform/issues/110
> Fix: 요청 핸들링 이슈들 해결 
